### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by juanagu** [mcnamee/react-native-starter-kit#131]
I'm new on React and started using this boilerplate, but when run command for install dependencies I see this warnings:

Info:
Master
version: "0.1.0".

![captura de pantalla 2018-01-06 a la s 15 04 32](https://user-images.githubusercontent.com/4689126/34642527-28ff19bc-f2f3-11e7-8dd4-d91ca90a9e18.png)

Did you ignore them?

**Comment by mcnamee** [comment]
Hi there,
Most, if not all of those warnings are caused from packages that are included from other packages (i.e. not directly caused by this repo).

I'd expect that over time as those packages update and we increment the package versions that we use, those specific warnings will disappear.

Feel free to have a play and if you find any solutions within this repo - submit a PR 😊
