### ISSUE TITLE
react native upgrade issue

### ISSUE THREAD

**Issue by gitsuraj** [mcnamee/react-native-starter-kit#170]
I just upgraded expo to 27.0.0 and react-native to 0.55.4. Expo app runs fine but I am getting multiple errors while running web version.

`ERROR in ./node_modules/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve 'Button' in '/Users/surajmaharjan/Projects/driverapp/node_modules/react-native/Libraries/react-native'
 @ ./node_modules/react-native/Libraries/react-native/react-native-implementation.js 20:24-41
 @ ./src/constants/location.js
 @ ./src/reducers/location.js
 @ ./src/reducers/index.js
 @ ./src/store/index.js
 @ ./src/web/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3001 webpack/hot/dev-server babel-polyfill ./src/web/index`

Can you point out the direction where I should look to fix this issue.

Regards

**Comment by kamalyadav11** [comment]
Check if you have imported Button from 'react-native'!

**Comment by mcnamee** [comment]
@gitsuraj The error indicates that the `Button` variable can't be resolved. As @kamalyadav11 indicates, please trace/debug to the (file) source causing the error, specifically that `Button` is imported from `react-native` ([Link](https://facebook.github.io/react-native/docs/button)).

In the meantime, I'll close due to inactivity
