### ISSUE TITLE
Question: How does the web version work?

### ISSUE THREAD

**Issue by prasanthsd** [mcnamee/react-native-starter-kit#192]
Hi,

I see that [React native for web](https://github.com/necolas/react-native-web) is not added to the dependencies. How does the web version work in this starter kit? Are there any documentation?

**Comment by mcnamee** [comment]
Hi @prasanthsd 
Only the documentation linked from the README.md

Essentially it simply combines an ejected __create-react-app__ along with __create-react-native-app__ in the same repo, so that they can share business logic, constants, assets etc, whilst being able to write platform specific view layers (i.e. use SCSS, Bootstrap, <div>'s <forms>'s etc for web and pure React Native code for native mobile).
